### ISSUE TITLE
isambard and budeff installation through pip 

### ISSUE THREAD

**Issue by broncio123** [isambard-uob/isambard#12]
When trying to install these packages using `pip`, the following errors appears:

```bash
pip install isambard
Collecting isambard
  Using cached https://files.pythonhosted.org/packages/9c/ba/636028b8e309e217e171016e34b2a9f5f0b37f3be916d02ad55f97cf4991/ISAMBARD-2.2.0.tar.gz
Requirement already satisfied: ampal in /mnt/storage/home/ba13026/anaconda3/lib/python3.6/site-packages (from isambard) (1.3.0)
Collecting budeff (from isambard)
  Using cached https://files.pythonhosted.org/packages/33/89/a7ea41131ab0db5c4232902ede026d5c21e05966b3abe59b84600fbb947d/BUDEFF-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6g9ul6lu/budeff/setup.py", line 17, in <module>
        long_description=readme(),
      File "/tmp/pip-install-6g9ul6lu/budeff/setup.py", line 11, in readme
        return inf.read()
      File "/mnt/storage/home/ba13026/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4726: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6g9ul6lu/budeff/
```

and 

```bash
pip install budeff
Collecting budeff
  Using cached https://files.pythonhosted.org/packages/33/89/a7ea41131ab0db5c4232902ede026d5c21e05966b3abe59b84600fbb947d/BUDEFF-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kkqqy1fw/budeff/setup.py", line 17, in <module>
        long_description=readme(),
      File "/tmp/pip-install-kkqqy1fw/budeff/setup.py", line 11, in readme
        return inf.read()
      File "/mnt/storage/home/ba13026/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4726: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kkqqy1fw/budeff/
```
As suggested on some forums, to solve the `Command "python setup.py egg_info" failed with error code 1` issue, I tried:

```bash
pip install --upgrade setuptools
pip install ez_setup
```
Nothing works so far.

I would appreciate your help. 

Bets wishes,
Broncio

**Comment by kls93** [comment]
Hi,

I'm going to close this now as it's an issue with installation on BlueCrystal rather than an issue with the isambard package.

Best,
Kathryn
